### ISSUE TITLE
Variable Time Event Selection

### ISSUE THREAD

**Issue by wunderk** [shashidarette/ProcessingPAL#4]
Hello,

Could you please confirm how events are selected to be included or excluded in variable times? Is it the approach of classifying bouts that occurred >= 50% during the self-reported period as being included in the variable time? (from Winkler et al. 2012)

Thank you.

**Comment by CharlotteEd** [comment]
Hi,
Thank you for your query. For Day Time Ranges and Variable Time Ranges, the data is split on the exact time threshold chosen, for example, if you want to isolate 9am-3pm, the data will be split on these thresholds even if a bout of behaviour spans this time thresholds. This means that the number of bouts would be split too. For example, if a bout of sitting started at 2.45pm and lasted until 3.40pm then 15 mins would be included before 3pm and this would be counted as 1 bout of sitting (and counted in bouts lasting 0-30mins) and 40 mins would be included after 3pm and this would be counted as 1 bout (and counted in bouts lasting 30-60mins).

The user instructions v1.2 221118 give some information on the decisions we made when calculating output variables (see page 21).

Thanks.

**Comment by shashidarette** [comment]
@wunderk 
Hi,

Request you to confirm if the query is clarified?

Thanks.

**Comment by wunderk** [comment]
Hello, 

Yes, thank you for the reminder. Your response provided the information that I was looking for. Thank you for your help.
