### ISSUE TITLE
About the algorithm validation of MVPA estimation

### ISSUE THREAD

**Issue by Bo-Huei** [shashidarette/ProcessingPAL#5]
Hi there,

I am investigating MVPA-related health benefits using your incredible algorithm.
Since I would like to make a journal publication, it could be necessary for me to provide a validation of the algorithm.
However, the reference you provide on the webpage only validate the waking wear time estimation but not MVPA estimation.

Would there be any publication could prove this MVPA or METs estimation?
Any information would be much appreciated.

Sincerely,
Bo-Huei Huang

**Comment by CharlotteEd** [comment]
Thank you for your query. There are no papers published describing or validating the MVPA calculation we use in Processing PAL. The MET values we use are the ones generated automatically by the PAL Technologies software and have been validated:

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5469371/

Kind Regards,

Charlotte
